SAMPLES:
    ["/scratch/brown/asm_mTriMan/data/hic/SRR8616893"]

prefix:
    mTriMan 

threads:
    24 

input_assembly:
     /scratch/brown/asm_mTriMan/assembly/ref/ncbi_dataset/data/GCA_030013775.1/GCA_030013775.1_ASM3001377v1_genomic.fna
